# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Install firefox
  community.general.snap:
    name: firefox
    classic: true
  become: true

- name: Create directory ~/.local/share/applications
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory
    recurse: true

- name: Firefox create profile default
  ansible.builtin.command:
    cmd: firefox --headless --createprofile default
    creates: "{{ ansible_env.HOME }}/snap/firefox/common/.mozilla/firefox/*default"

- name: Query location of generated profile
  ansible.builtin.find:
    file_type: directory
    paths: "{{ ansible_env.HOME }}/snap/firefox/common/.mozilla/firefox/"
    # note the . prefix before the name, which indicates the profile has a random prefix
    patterns: "*.default"
    depth: 1
  register: profiles

- name: Move Firefox profile to folder default
  when: profiles.matched > 0
  ansible.builtin.command:
    cmd: mv {{ profiles.files[0].path }} {{ ansible_env.HOME }}/snap/firefox/common/.mozilla/firefox/default
    creates: "{{ ansible_env.HOME }}/snap/firefox/common/.mozilla/firefox/default"

- name: Set profile path in Firefox profiles.ini
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/snap/firefox/common/.mozilla/firefox/profiles.ini"
    regexp: '^Path=[a-zA-Z0-9]+\.default$'
    line: "Path=default"

- name: Add firefox desktop shortcut
  ansible.builtin.template:
    src: Firefox.desktop.j2
    dest: "{{ ansible_env.HOME }}/.local/share/applications/Firefox.desktop"
