# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Apt update cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr

- name: Install desktop packages
  ansible.builtin.import_tasks: desktop-packages.yml

- name: Disable Wayland protocol
  when: ubuntu_desktop_disable_wayland
  ansible.builtin.include_tasks: wayland-disable.yml

- name: Install X11 video dummy
  when: ubuntu_desktop_configure_x11_dummy
  ansible.builtin.include_tasks: x11-dummy.yml

- name: Install X11 OpenGL
  when: ubuntu_desktop_configure_x11_opengl
  ansible.builtin.include_tasks: x11-opengl.yml

# Avoids "Authentication is required to create color profile" on remote login
# and enables basic package management.
# see https://c-nergy.be/blog/?p=14051
- name: Configure policy kit for remote users
  become: true
  with_items:
    - 45-allow-colord.pkla
    - 46-allow-update-repo.pkla
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/polkit-1/localauthority.conf.d/

- name: Disable gnome-initial-setup
  when: ubuntu_disable_gnome_initial_setup
  ansible.builtin.include_tasks: gnome-initial-setup.yml

- name: Configure desktop wallpaper
  when: ubuntu_desktop_configure_wallpaper
  ansible.builtin.include_tasks: wallpaper.yml
