---
- name: Apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
  become: true

- name: Apt install Ubuntu Desktop
  ansible.builtin.apt:
    pkg:
      - ubuntu-desktop-minimal
      - gdm3
    install_recommends: false
  become: true
  notify: Restart X11

- name: Disable Wayland protocol
  ansible.builtin.include_tasks: disable-wayland.yml
  when: ubuntu_desktop_disable_wayland

- name: Configure desktop wallpaper
  ansible.builtin.include_tasks: wallpaper.yml
  when: ubuntu_desktop_configure_wallpaper

- name: Configure Gnome shell on login
  ansible.builtin.include_tasks: xdg-rc.yml
  when: ubuntu_desktop_xdg_rc

- name: Query restart required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: stat_result
  changed_when: stat_result.stat.exists
  notify:
    - Restart server

- name: Install gnome-software
  ansible.builtin.apt:
    pkg:
      - gnome-software
      - gnome-software-plugin-snap
  become: true

- name: Install Firefox
  when: ubuntu_desktop_install_firefox
  ansible.builtin.include_tasks: firefox.yml