# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Query restart required
  register: _stat_result
  notify: "xronos_ubuntu_desktop_ansible : Schedule reboot"
  changed_when: false
  ansible.builtin.stat:
    path: /var/run/reboot-required

- name: Reboot
  when: _stat_result.stat.exists
  become: true
  ansible.builtin.reboot:
