# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
# force the login screen to use x11 (required by NICE-DCV)
- name: GDM3 disable Wayland protocol
  register: _wayland
  become: true
  ansible.builtin.lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: "^(#).*WaylandEnable="
    line: "WaylandEnable=false"

- name: Restart gdm3 to apply change to Wayland protocol
  when: _wayland.changed
  become: true
  ansible.builtin.service:
    name: gdm3
    state: "{{ _wayland.changed | ternary('restarted', 'started') }}"
