---
- name: Configure ~/.xsessionrc for Gnome shell
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.xsessionrc"
    line: "{{ item }}"
    create: true
  with_items:
    - "export GNOME_SHELL_SESSION_MODE=ubuntu"
    - "export XDG_CURRENT_DESKTOP=ubuntu:GNOME"
    - "export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg"

# Avoids "Authentication is required to create color profile" on remote login
# and enables basic package management.
# see https://c-nergy.be/blog/?p=14051
- name: Allow remote users to access colord
  ansible.builtin.copy:
    src: 45-allow-colord.pkla
    dest: /etc/polkit-1/localauthority/50-local.d
  become: true

- name: Allow remote users to access package management
  ansible.builtin.copy:
    src: 46-allow-update-repo.pkla
    dest: /etc/polkit-1/localauthority/50-local.d
  become: true
