# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Schedule reboot
  when: inventory_hostname != "localhost"
  become: true
  ansible.builtin.copy:
    dest: /var/run/reboot-required
    content: ""
    force: false
